question_data = [
    {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Snakes and Ladders was originally created in India?",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The game &quot;Battlefield 1&quot; takes place during World War I.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                      "question": "Cucumbers are usually more than 90% water.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The ultimate phrase used by Pharah from Overwatch is: &quot;Justice rains from above!&quot;",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                      "question": "Toronto is the capital city of the North American country of Canada.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Mythology", "type": "boolean", "difficulty": "hard",
                                      "question": "Rannamaari was a sea demon that haunted the people of the Maldives and had to be appeased monthly with the sacrifice of a virgin girl.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Danganronpa 2: Goodbye Despair featured all of the surviving students from the first game.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                                      "question": "&quot;The Division Bell&quot; is the final album of the progressive rock band Pink Floyd.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Sports", "type": "boolean", "difficulty": "easy",
                                      "question": "Roger Federer is a famous soccer player.", "correct_answer": "False",
                                      "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                      "question": "Stevie Wonder&#039;s real name is Stevland Hardaway Morris.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean",
                                      "difficulty": "medium", "question": "In Rocket League, you can play Basketball.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
                                      "question": "All of these maps were in &quot;Tom Clancy&#039;s Rainbow Six Siege&quot; on its initial release: House, Clubhouse, Border, Consulate.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                                      "difficulty": "hard",
                                      "question": "Druid is a mage class in &quot;Log Horizon&quot;.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "Actor Tommy Chong served prison time.", "correct_answer": "True",
                                      "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The ghosts in &quot;Pac-Man&quot; and &quot;Ms. Pac-Man&quot; have completely different behavior.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                      "question": "The scientific name for the Southern Lights is Aurora Australis?",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
                                      "question": "A scalene triangle has two sides of equal length.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The shotgun appears in every numbered Resident Evil game.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]}]
